# Generated by Django 3.2 on 2023-07-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('desc', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('logo', models.ImageField(upload_to='company/logo', verbose_name='logo')),
                ('call_us', models.CharField(max_length=25, verbose_name='Call_Us')),
                ('fb_link', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('insta_link', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin_link', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('twit_link', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('emails', models.TextField(blank=True, max_length=100, null=True, verbose_name='Emails')),
                ('numbers', models.TextField(blank=True, max_length=100, null=True, verbose_name='Numbers')),
                ('address', models.TextField(blank=True, max_length=100, null=True, verbose_name='Address')),
            ],
        ),
    ]
