# Generated by Django 3.2 on 2023-07-25 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='company',
            name='numbers',
        ),
    ]
