# Generated by Django 3.2 on 2023-08-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20230725_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='company',
            name='call_us',
            field=models.CharField(max_length=25, verbose_name='تواصل معنا'),
        ),
        migrations.AlterField(
            model_name='company',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الالكتروني'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fb_link',
            field=models.URLField(blank=True, null=True, verbose_name='فيسبوك'),
        ),
        migrations.AlterField(
            model_name='company',
            name='insta_link',
            field=models.URLField(blank=True, null=True, verbose_name='انستجرام'),
        ),
        migrations.AlterField(
            model_name='company',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True, verbose_name='لينكدان'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='company/logo', verbose_name='اللوجو'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='company',
            name='twit_link',
            field=models.URLField(blank=True, null=True, verbose_name='تويتر'),
        ),
    ]
