# Generated by Django 3.2 on 2023-08-07 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='about/images', verbose_name='الصوره'),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='about',
            name='our_goal',
            field=models.TextField(verbose_name='هدفنا'),
        ),
        migrations.AlterField(
            model_name='about',
            name='what_we_do',
            field=models.TextField(verbose_name='ماذا نفعل ؟'),
        ),
        migrations.AlterField(
            model_name='about',
            name='who_we_are',
            field=models.TextField(verbose_name='من نحن ؟'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='اجابه'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=500, verbose_name='سوال'),
        ),
        migrations.CreateModel(
            name='Subscribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الالكتروني')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'Subscribtion',
                'verbose_name_plural': 'Subscribers',
            },
        ),
    ]
