# Generated by Django 3.2 on 2023-07-22 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('image', models.ImageField(upload_to='category/images', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('image', models.ImageField(upload_to='place/images', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('image', models.ImageField(upload_to='property/images', verbose_name='main_image')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('descritpion', models.TextField(verbose_name='descritpion')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proerty_category', to='property.category', verbose_name='category')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_places', to='property.place', verbose_name='places')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0, verbose_name='rate')),
                ('content', models.CharField(max_length=150, verbose_name='content')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_Reviews', to='property.property', verbose_name='property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property/images', verbose_name='image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='property.property', verbose_name='property')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('date_from', models.DateField(default=django.utils.timezone.now, verbose_name='booked from')),
                ('date_to', models.DateField(default=django.utils.timezone.now, verbose_name='booked to')),
                ('guests', models.IntegerField(choices=[(4, 4), (5, 5), (3, 3), (2, 2), (1, 1)], verbose_name='guests')),
                ('childerns', models.IntegerField(choices=[(4, 4), (5, 5), (3, 3), (2, 2), (1, 1)], verbose_name='childerns')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_booked', to='property.property', verbose_name='property')),
            ],
        ),
    ]
