# Generated by Django 3.2 on 2023-07-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
    ]
