# Generated by Django 3.2 on 2023-07-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedRooms',
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['price']},
        ),
    ]
