# Generated by Django 3.2 on 2023-07-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='owner',
            new_name='user',
        ),
    ]
