# Generated by Django 3.2 on 2023-07-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
