# Generated by Django 3.2 on 2023-08-02 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='avilablity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='avilabilty'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='rate'),
        ),
    ]
