# Generated by Django 3.2 on 2023-08-07 19:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0012_alter_book_childerns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='childerns',
            field=models.IntegerField(blank=True, choices=[(4, 4), (5, 5), (3, 3), (2, 2), (1, 1)], null=True, verbose_name='الاطفال'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='نشأت'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='حجزت من'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='حجزت الي'),
        ),
        migrations.AlterField(
            model_name='book',
            name='guests',
            field=models.IntegerField(choices=[(4, 4), (5, 5), (3, 3), (2, 2), (1, 1)], verbose_name='الضيوف'),
        ),
        migrations.AlterField(
            model_name='book',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_booked', to='property.property', verbose_name='الوحده'),
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_user', to=settings.AUTH_USER_MODEL, verbose_name='مستخدم'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='الصوره التعبيريه'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(upload_to='place/images', verbose_name='الصوره'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='property',
            name='avilablity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='متاح ؟'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_category', to='property.category', verbose_name='الفئه'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='نشأت'),
        ),
        migrations.AlterField(
            model_name='property',
            name='descritpion',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='property/images', verbose_name='الصوره'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالك الوحده'),
        ),
        migrations.AlterField(
            model_name='property',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_places', to='property.place', verbose_name='المكان'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=0, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(upload_to='property/images', verbose_name='الصوره'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='property.property', verbose_name='الوحده'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to=settings.AUTH_USER_MODEL, verbose_name='الموءلف'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=150, verbose_name='التعليق'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='نشأت'),
        ),
        migrations.AlterField(
            model_name='review',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_Reviews', to='property.property', verbose_name='الوحده'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='التقييم'),
        ),
    ]
